### PR TITLE
report errors to users when managing pools

### PR DESCRIPTION
**Pull request by akostadinov**
seems like `save` does in fact raise errors on database failed transaction instead of putting only storing them

### CODE REVIEW

**Comment by maybelinot** [comment]
Strange thing that `save` separate  failed transaction:
if I'll try to save pool with empty resource field  it will just save error message to pool and return false,
but when I'd like to save pool with already existed name:resource fields it will raise an error..
Can we manage this behavior somehow?

btw, when I'm trying to save pool with existing name:resource it will raise an error, but anyway will update field on the page, after refresh everything returns to original state..

otherwise LGTM

**Comment by akostadinov** [comment]
Thanks for exploratory testing and finding the issue. I'll try to replicate according to your instructions.

**Comment by akostadinov** [comment]
Behavior you describe about `save` is as far as I can tell by design although it also doesn't make much sense to me.

About the issue where record is updated on screen but refresh rings it back to what it should be appears to me like a bug. Because `@pool.persisted?` returns true while it must be false IMO. Provided the object is not in the database, how come Rails shows it as persisted??

**Comment by akostadinov** [comment]
Hi, I have updated the pull and now trying to edit pool entry into a duplicate will not update it in UI (neither in DB). Thanks a lot for spotting this. First part of your comments, I don't see them as something we can help.
Do you think there's anything more before we can merge?

P.S. I just didn't understand well what is `persisted?` actually meaning. It in fact does return true even after attribute changes.

**Comment by maybelinot** [comment]
@akostadinov I hadn't thought about any actions regarding first paragraph. Just wrote it FYI, if you didn't know that before, but I think you did =)

changes LGTM!

**Comment by akostadinov** [comment]
Thank you for review!

**Pull request merged**
